### ISSUE TITLE
dockerFile

### ISSUE THREAD

**Issue by joeblew99** [arvitaly/gopherjs-electron#1]
@arvitaly thanks for putting this on github. Really useful.

I want to change this image to use a smaller base. Alpine linux.
https://hub.docker.com/r/arvitaly/electron-go/

Could you add it this this repo or send to me ?

-- I am going to do some work on it with regards to Cordova also.

**Comment by arvitaly** [comment]
Hi, @joeblew99 
Repo for docker-image here - https://github.com/arvitaly/docker-electron-go

**Comment by joeblew99** [comment]
thanks @arvitaly 

Really useful.
I am going to get this working on Arm also, and will try to push it back to you if you want.
Let me know.

**Comment by joeblew99** [comment]
It does not like golang latest.
this is likely because gopherjs is undergoing heavy change in terms of the way its build tooling integrates with golang build tooling.

I will change this to go 1.7 for now
